"""Add devices and reservations

Revision ID: 8d08469a5c77
Revises: 202501010101
Create Date: 2026-01-01 21:58:50.252580

"""
from alembic import op
import sqlalchemy as sa



revision = '8d08469a5c77'
down_revision = '202501010101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_no', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=False),
    sa.Column('usage', sa.Text(), nullable=False),
    sa.Column('rental_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'IN_USE', 'MAINTENANCE', 'SCRAPPED', name='device_status', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_no'), 'devices', ['device_no'], unique=True)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='reservation_status', native_enum=False), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'WAIVED', name='payment_status', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('uq_users_account'), 'users', type_='unique')
    op.create_index(op.f('ix_users_account'), 'users', ['account'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_account'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_account'), 'users', ['account'])
    op.drop_table('reservations')
    op.drop_index(op.f('ix_devices_device_no'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
