"""add_generated_reports_table

Revision ID: b1245294dfe0
Revises: 20260118_merge_heads
Create Date: 2026-01-15 09:00:58.204454

"""
from alembic import op
import sqlalchemy as sa



revision = 'b1245294dfe0'
down_revision = '20260118_merge_heads'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('WEEKLY', 'MONTHLY', 'YEARLY', name='reporttype'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_reports_id'), ['id'], unique=False)

    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_windows_device_time'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_to_user_created'))
        batch_op.drop_index(batch_op.f('ix_notifications_to_user_unread'))
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.create_index(batch_op.f('ix_notifications_to_user_unread'), ['to_user_id', 'is_read', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_to_user_created'), ['to_user_id', 'created_at'], unique=False)

    with op.batch_alter_table('maintenance_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_windows_device_time'), ['device_id', 'start_time', 'end_time'], unique=False)

    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_id'))

    op.drop_table('generated_reports')
    # ### end Alembic commands ###
