"""添加系统配置表

Revision ID: cc6b1c04c492
Revises: 20260112_finance_integration
Create Date: 2026-01-12 21:32:41.392945

"""
from alembic import op
import sqlalchemy as sa



revision = 'cc6b1c04c492'
down_revision = '20260112_finance_integration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PENDING', 'ADVISOR_APPROVED', 'ADMIN_APPROVED', 'HEAD_APPROVED', 'APPROVED', 'REJECTED', 'RETURNED', 'EFFECTIVE', 'BORROWED', 'COMPLETED', 'CANCELLED', name='reservation_status', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('current_step',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADVISOR', 'ADMIN', 'HEAD', 'PAYMENT', 'FINAL', name='approval_step', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('NOT_REQUIRED', 'PENDING', 'PAID', 'REFUNDED', 'WAIVED', name='payment_status', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('payment_status',
               existing_type=sa.Enum('NOT_REQUIRED', 'PENDING', 'PAID', 'REFUNDED', 'WAIVED', name='payment_status', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.alter_column('current_step',
               existing_type=sa.Enum('ADVISOR', 'ADMIN', 'HEAD', 'PAYMENT', 'FINAL', name='approval_step', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ADVISOR_APPROVED', 'ADMIN_APPROVED', 'HEAD_APPROVED', 'APPROVED', 'REJECTED', 'RETURNED', 'EFFECTIVE', 'BORROWED', 'COMPLETED', 'CANCELLED', name='reservation_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
